# Form implementation generated from reading ui file 'defaultView.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_NuevoRegistro(object):
    def setupUi(self, NuevoRegistro):
        NuevoRegistro.setObjectName("NuevoRegistro")
        NuevoRegistro.resize(455, 622)
        NuevoRegistro.setStyleSheet("Background: white")
        self.centralwidget = QtWidgets.QWidget(parent=NuevoRegistro)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 471, 621))
        self.frame.setAcceptDrops(False)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("Background: white ")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.frameNavegacion = QtWidgets.QFrame(parent=self.frame)
        self.frameNavegacion.setGeometry(QtCore.QRect(10, 510, 431, 101))
        self.frameNavegacion.setStyleSheet("Background: white;\n"
"border-top:  1px solid #E5E7E9;")
        self.frameNavegacion.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameNavegacion.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameNavegacion.setObjectName("frameNavegacion")
        self.btnChat = QtWidgets.QPushButton(parent=self.frameNavegacion)
        self.btnChat.setGeometry(QtCore.QRect(10, 20, 71, 51))
        self.btnChat.setStyleSheet("image: url(./assets/images/chat.png); \n"
"border: none;\n"
"\n"
"")
        self.btnChat.setText("")
        self.btnChat.setObjectName("btnChat")
        self.b = QtWidgets.QPushButton(parent=self.frameNavegacion)
        self.b.setGeometry(QtCore.QRect(100, 20, 71, 51))
        self.b.setStyleSheet("image: url(./assets/images/trivia.png);\n"
"border: none;")
        self.b.setText("")
        self.b.setObjectName("b")
        self.btnCapturar = QtWidgets.QPushButton(parent=self.frameNavegacion)
        self.btnCapturar.setGeometry(QtCore.QRect(190, 20, 71, 51))
        self.btnCapturar.setStyleSheet("image: url(./assets/images/capturar.png);\n"
"border: none;")
        self.btnCapturar.setText("")
        self.btnCapturar.setObjectName("btnCapturar")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.frameNavegacion)
        self.pushButton_7.setGeometry(QtCore.QRect(280, 20, 71, 51))
        self.pushButton_7.setStyleSheet("image: url(./assets/images/wiki.png);\n"
"border: none;")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.frameNavegacion)
        self.pushButton_8.setGeometry(QtCore.QRect(370, 20, 71, 51))
        self.pushButton_8.setStyleSheet("image: url(./assets/images/historial.png);\n"
"border: none;")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        NuevoRegistro.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=NuevoRegistro)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 455, 25))
        self.menubar.setObjectName("menubar")
        NuevoRegistro.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=NuevoRegistro)
        self.statusbar.setObjectName("statusbar")
        NuevoRegistro.setStatusBar(self.statusbar)

        self.retranslateUi(NuevoRegistro)
        QtCore.QMetaObject.connectSlotsByName(NuevoRegistro)

    def retranslateUi(self, NuevoRegistro):
        _translate = QtCore.QCoreApplication.translate
        NuevoRegistro.setWindowTitle(_translate("NuevoRegistro", "Nuevo Registro"))