# Form implementation generated from reading ui file 'ViewAnimalFound.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NuevoRegistro(object):
    def setupUi(self, NuevoRegistro):
        NuevoRegistro.setObjectName("NuevoRegistro")
        NuevoRegistro.resize(453, 611)
        NuevoRegistro.setStyleSheet("Background: white")
        self.centralwidget = QtWidgets.QWidget(parent=NuevoRegistro)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(10, 0, 471, 621))
        self.frame.setAcceptDrops(False)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("Background: white ")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.frameNavegacion = QtWidgets.QFrame(parent=self.frame)
        self.frameNavegacion.setGeometry(QtCore.QRect(10, 510, 451, 101))
        self.frameNavegacion.setStyleSheet("Background: white;\n"
"border-top:  1px solid #E5E7E9;")
        self.frameNavegacion.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameNavegacion.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameNavegacion.setObjectName("frameNavegacion")
        self.btnChat = QtWidgets.QPushButton(parent=self.frameNavegacion)
        self.btnChat.setGeometry(QtCore.QRect(10, 20, 71, 51))
        self.btnChat.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnChat.setStyleSheet("image: url(./assets/images/chat.png); \n"
"border: none;\n"
"\n"
"")
        self.btnChat.setText("")
        self.btnChat.setObjectName("btnChat")
        self.btnTrivia = QtWidgets.QPushButton(parent=self.frameNavegacion)
        self.btnTrivia.setGeometry(QtCore.QRect(100, 20, 71, 51))
        self.btnTrivia.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnTrivia.setStyleSheet("image: url(./assets/images/trivia.png);\n"
"border: none;")
        self.btnTrivia.setText("")
        self.btnTrivia.setObjectName("btnTrivia")
        self.btnCapturar = QtWidgets.QPushButton(parent=self.frameNavegacion)
        self.btnCapturar.setGeometry(QtCore.QRect(190, 20, 71, 51))
        self.btnCapturar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCapturar.setStyleSheet("image: url(./assets/images/capturar.png);\n"
"border: none;")
        self.btnCapturar.setText("")
        self.btnCapturar.setObjectName("btnCapturar")
        self.btnWiki = QtWidgets.QPushButton(parent=self.frameNavegacion)
        self.btnWiki.setGeometry(QtCore.QRect(280, 20, 71, 51))
        self.btnWiki.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnWiki.setStyleSheet("image: url(./assets/images/wiki.png);\n"
"border: none;")
        self.btnWiki.setText("")
        self.btnWiki.setObjectName("btnWiki")
        self.btnHistorial = QtWidgets.QPushButton(parent=self.frameNavegacion)
        self.btnHistorial.setGeometry(QtCore.QRect(370, 20, 71, 51))
        self.btnHistorial.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnHistorial.setStyleSheet("image: url(./assets/images/historial.png);\n"
"border: none;")
        self.btnHistorial.setText("")
        self.btnHistorial.setObjectName("btnHistorial")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 411, 491))
        self.frame_2.setStyleSheet("border: 1px solid black; border-radius: 10px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setLineWidth(4)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        self.label.setGeometry(QtCore.QRect(150, 10, 188, 38))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("border: none;\n"
"font: 87 18pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.txtImagenAnimal = QtWidgets.QLabel(parent=self.frame_2)
        self.txtImagenAnimal.setGeometry(QtCore.QRect(130, 50, 151, 161))
        self.txtImagenAnimal.setStyleSheet("border: 2px solid black; border-radius: 10px")
        self.txtImagenAnimal.setText("")
        self.txtImagenAnimal.setObjectName("txtImagenAnimal")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(30, 248, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border: none;\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(30, 295, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border: none;\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(30, 350, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border: none;\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(30, 396, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border: none;\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.txtDescripcion = QtWidgets.QTextBrowser(parent=self.frame_2)
        self.txtDescripcion.setGeometry(QtCore.QRect(130, 240, 271, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.txtDescripcion.setFont(font)
        self.txtDescripcion.setStyleSheet("border: none;\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);")
        self.txtDescripcion.setObjectName("txtDescripcion")
        self.txtHabitat = QtWidgets.QTextBrowser(parent=self.frame_2)
        self.txtHabitat.setGeometry(QtCore.QRect(130, 295, 271, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.txtHabitat.setFont(font)
        self.txtHabitat.setStyleSheet("border: none;\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);")
        self.txtHabitat.setObjectName("txtHabitat")
        self.txtEspecies = QtWidgets.QTextBrowser(parent=self.frame_2)
        self.txtEspecies.setGeometry(QtCore.QRect(130, 394, 271, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.txtEspecies.setFont(font)
        self.txtEspecies.setStyleSheet("border: none;\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);")
        self.txtEspecies.setObjectName("txtEspecies")
        self.txtDieta = QtWidgets.QTextBrowser(parent=self.frame_2)
        self.txtDieta.setGeometry(QtCore.QRect(130, 350, 271, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.txtDieta.setFont(font)
        self.txtDieta.setStyleSheet("border: none;\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);")
        self.txtDieta.setObjectName("txtDieta")
        self.btnPlay = QtWidgets.QPushButton(parent=self.frame_2)
        self.btnPlay.setGeometry(QtCore.QRect(100, 450, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnPlay.setFont(font)
        self.btnPlay.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnPlay.setStyleSheet("background-color: rgb(135, 171, 152);\n"
"border-radius: 10px;\n"
"border:none;\n"
"font: 9pt \"Papyrus\";\n"
"")
        self.btnPlay.setObjectName("btnPlay")
        NuevoRegistro.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=NuevoRegistro)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 453, 25))
        self.menubar.setObjectName("menubar")
        NuevoRegistro.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=NuevoRegistro)
        self.statusbar.setObjectName("statusbar")
        NuevoRegistro.setStatusBar(self.statusbar)

        self.retranslateUi(NuevoRegistro)
        QtCore.QMetaObject.connectSlotsByName(NuevoRegistro)

    def retranslateUi(self, NuevoRegistro):
        _translate = QtCore.QCoreApplication.translate
        NuevoRegistro.setWindowTitle(_translate("NuevoRegistro", "Nuevo Registro"))
        self.label.setText(_translate("NuevoRegistro", "Nombre"))
        self.label_3.setText(_translate("NuevoRegistro", "Descripción:"))
        self.label_4.setText(_translate("NuevoRegistro", "Habitat.......:"))
        self.label_5.setText(_translate("NuevoRegistro", "Dieta...........:"))
        self.label_6.setText(_translate("NuevoRegistro", "Especies.....:"))
        self.txtDescripcion.setHtml(_translate("NuevoRegistro", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.85455pt;\">Esta es una descripción corta de como se ve le animal y los colores que suele tener</span></p></body></html>"))
        self.txtHabitat.setHtml(_translate("NuevoRegistro", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.85455pt;\">Esta es una descripción del habitat del animal</span></p></body></html>"))
        self.txtEspecies.setHtml(_translate("NuevoRegistro", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.85455pt;\">Si es que tiene especies</span></p></body></html>"))
        self.txtDieta.setHtml(_translate("NuevoRegistro", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.85455pt;\">Su dieta</span></p></body></html>"))
        self.btnPlay.setText(_translate("NuevoRegistro", "PLAY"))
